// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Travel.InfraStructure.EfCore.Common;

#nullable disable

namespace Travel.InfraStructure.EfCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250603091830_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Travel.Domain.Core.Entities.CheckList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChekListType")
                        .HasColumnType("int");

                    b.Property<int>("TripType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CheckLists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChekListType = 1,
                            TripType = 4
                        },
                        new
                        {
                            Id = 2,
                            ChekListType = 2,
                            TripType = 1
                        },
                        new
                        {
                            Id = 3,
                            ChekListType = 1,
                            TripType = 2
                        },
                        new
                        {
                            Id = 4,
                            ChekListType = 2,
                            TripType = 3
                        },
                        new
                        {
                            Id = 5,
                            ChekListType = 1,
                            TripType = 5
                        });
                });

            modelBuilder.Entity("Travel.Domain.Core.Entities.CheckListTrip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CheckListId")
                        .HasColumnType("int");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("bit");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CheckListId");

                    b.HasIndex("TripId");

                    b.ToTable("CheckListTrips");
                });

            modelBuilder.Entity("Travel.Domain.Core.Entities.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<int>("TripType")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Destination = "tehran",
                            End = new DateTime(2025, 5, 9, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2025, 5, 6, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            TripType = 4,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Destination = "ardabil",
                            End = new DateTime(2025, 5, 9, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2025, 5, 6, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            TripType = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Destination = "mashhad",
                            End = new DateTime(2025, 5, 9, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Start = new DateTime(2025, 5, 6, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            TripType = 2,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Travel.Domain.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "test1@gmail.com",
                            Name = "name1",
                            Password = "123"
                        },
                        new
                        {
                            Id = 2,
                            Email = "test2@gmail.com",
                            Name = "name2",
                            Password = "123"
                        },
                        new
                        {
                            Id = 3,
                            Email = "test3@gmail.com",
                            Name = "name3",
                            Password = "123"
                        });
                });

            modelBuilder.Entity("Travel.Domain.Core.Entities.CheckListTrip", b =>
                {
                    b.HasOne("Travel.Domain.Core.Entities.CheckList", "CheckList")
                        .WithMany("CheckListTrips")
                        .HasForeignKey("CheckListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Travel.Domain.Core.Entities.Trip", "Trip")
                        .WithMany("CheckListTrips")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckList");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("Travel.Domain.Core.Entities.Trip", b =>
                {
                    b.HasOne("Travel.Domain.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Travel.Domain.Core.Entities.CheckList", b =>
                {
                    b.Navigation("CheckListTrips");
                });

            modelBuilder.Entity("Travel.Domain.Core.Entities.Trip", b =>
                {
                    b.Navigation("CheckListTrips");
                });
#pragma warning restore 612, 618
        }
    }
}
